#!/bin/bash

WALL=$(find ~/Pictures/Wallpapers -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)

xwallpaper --zoom $WALL
wal -q -c
wal -q -i $WALL
xdotool key super+F5

rm ~/.config/BetterDiscord/themes/*
rm ~/.config/Vencord/themes/*
pywal-discord -d
mv ~/.config/BetterDiscord/themes/* ~/.config/Vencord/themes

starttree.py

pkill st
st &
