alias c="clear"
alias pf="pfetch"
alias ff="fastfetch --logo-type small --logo-padding-top 3 --logo-padding 4"
alias fastfetch="fastfetch --logo-type small --logo-padding-top 3 --logo-padding 4"
alias ls="eza --icons"
alias la="eza -a --icons"
alias ll="eza -al --icons"
alias lt="eza -a --tree --level=2 --icons"
#alias shutdown="systemctl poweroff"
alias wifi="nmtui"
alias h="htop"
alias b="btop"
alias m="micro"
alias e="yazi"
alias clear="clear && fastfetch --logo-type small --logo-padding-top 3 --logo-padding 4"
alias shutdown="shutdown -P now"
alias image="termvisage"
alias l="eza --icons"
alias bluetooth="systemctl start bluetooth"
alias install="sudo pacman -S"
alias delete="sudo pacman -Rns"
alias mempush="adb push ~/.config/PCSX2/memcards/* /sdcard/Android/data/xyz.aethersx2.android/files/memcards/"
alias mempull="adb pull /sdcard/Android/data/xyz.aethersx2.android/files/memcards/Mcd001.ps2 /sdcard/Android/data/xyz.aethersx2.android/files/memcards/Mcd002.ps2 ~/.config/PCSX2/memcards/"
alias enum4linux="~/repos/enum4linux/enum4linux.pl"
alias wireshark="wireshark --style Adwaita-Dark"

# GIT
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gst="git stash"
alias gsp="git stash; git pull"
alias gchk="git checkout"
alias gcred="git config credential.helper store"

# UTILS
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# OTHER
alias update="$HOME/Dots/Scripts/Settings/update.sh"
alias settings="$HOME/Dots/Scripts/Settings/settings.sh"
alias updatepkg='yay -Syu'
